name: base
channels:
  - defaults
dependencies:
  - python=3.8.0
  - _ipyw_jlab_nb_ext_conf
  - _libgcc_mutex
  - alabaster
  - anaconda
  - anaconda-client
  - anaconda-navigator
  - anaconda-project
  - anyio
  - appdirs
  - argh
  - argon2-cffi
  - asn1crypto
  - astroid
  - astropy
  - async_generator
  - atomicwrites
  - attrs
  - autopep8
  - babel
  - backcall
  - backports
  - backports.functools_lru_cache
  - backports.shutil_get_terminal_size
  - backports.tempfile
  - backports.weakref
  - beautifulsoup4
  - bitarray
  - bkcharts
  - black
  - blas
  - bleach
  - blosc
  - bokeh
  - boto
  - bottleneck
  - brotlipy
  - bzip2
  - c-ares
  - ca-certificates
  - cairo
  - certifi
  - cffi
  - chardet
  - click
  - cloudpickle
  - clyent
  - colorama
  - conda
  - conda-build
  - conda-content-trust
  - conda-env
  - conda-package-handling
  - conda-repo-cli
  - conda-token
  - conda-verify
  - contextlib2
  - cryptography
  - curl
  - cycler
  - cython
  - cytoolz
  - dask
  - dask-core
  - dbus
  - decorator
  - defusedxml
  - diff-match-patch
  - distributed
  - docutils
  - entrypoints
  - et_xmlfile
  - expat
  - fastcache
  - filelock
  - flake8
  - flask
  - fontconfig
  - freetype
  - fribidi
  - fsspec
  - future
  - get_terminal_size
  - gevent
  - glib
  - glob2
  - gmp
  - gmpy2
  - graphite2
  - greenlet
  - gst-plugins-base
  - gstreamer
  - h5py
  - harfbuzz
  - hdf5
  - heapdict
  - html5lib
  - icu
  - idna
  - imageio
  - imagesize
  - importlib-metadata
  - importlib_metadata
  - iniconfig
  - intel-openmp
  - intervaltree
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - isort
  - itsdangerous
  - jbig
  - jdcal
  - jedi
  - jeepney
  - jinja2
  - joblib
  - jpeg
  - json5
  - jsonschema
  - jupyter
  - jupyter-packaging
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyter_server
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - jupyterlab_widgets
  - keyring
  - kiwisolver
  - krb5
  - lazy-object-proxy
  - lcms2
  - ld_impl_linux-64
  - libarchive
  - libcurl
  - libedit
  - libev
  - libffi
  - libgfortran-ng
  - liblief
  - libpng
  - libsodium
  - libspatialindex
  - libssh2
  - libstdcxx-ng
  - libtiff
  - libtool
  - libuuid
  - libuv
  - libwebp-base
  - libxcb
  - libxml2
  - libxslt
  - llvmlite
  - locket
  - lxml
  - lz4-c
  - lzo
  - markupsafe
  - matplotlib
  - matplotlib-base
  - mccabe
  - mistune
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - mock
  - more-itertools
  - mpc
  - mpfr
  - mpmath
  - msgpack-python
  - multipledispatch
  - mypy_extensions
  - navigator-updater
  - nbclassic
  - nbclient
  - nbconvert
  - nbformat
  - ncurses
  - nest-asyncio
  - networkx
  - nltk
  - nose
  - notebook
  - numba
  - numexpr
  - numpy
  - numpy-base
  - numpydoc
  - olefile
  - openpyxl
  - openssl
  - packaging
  - pandas
  - pandoc
  - pandocfilters
  - pango
  - parso
  - partd
  - patchelf
  - path
  - path.py
  - pathlib2
  - pathspec
  - patsy
  - pcre
  - pep8
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pixman
  - pkginfo
  - pluggy
  - ply
  - prometheus_client
  - prompt-toolkit
  - prompt_toolkit
  - psutil
  - ptyprocess
  - py
  - py-lief
  - pycodestyle
  - pycosat
  - pycparser
  - pycurl
  - pydocstyle
  - pyerfa
  - pyflakes
  - pygments
  - pylint
  - pyls-black
  - pyls-spyder
  - pyodbc
  - pyopenssl
  - pyparsing
  - pyqt
  - pyrsistent
  - pysocks
  - pytables
  - pytest
  - python
  - python-dateutil
  - python-jsonrpc-server
  - python-language-server
  - python-libarchive-c
  - pytz
  - pywavelets
  - pyxdg
  - pyyaml
  - pyzmq
  - qdarkstyle
  - qt
  - qtawesome
  - qtconsole
  - qtpy
  - rasterio
  - readline
  - regex
  - requests
  - ripgrep
  - rope
  - rtree
  - ruamel_yaml
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - secretstorage
  - send2trash
  - setuptools
  - simplegeneric
  - singledispatch
  - sip
  - six
  - sniffio
  - snowballstemmer
  - sortedcollections
  - sortedcontainers
  - soupsieve
  - sphinx
  - sphinxcontrib
  - sphinxcontrib-applehelp
  - sphinxcontrib-devhelp
  - sphinxcontrib-htmlhelp
  - sphinxcontrib-jsmath
  - sphinxcontrib-qthelp
  - sphinxcontrib-serializinghtml
  - sphinxcontrib-websupport
  - spyder
  - spyder-kernels
  - sqlalchemy
  - sqlite
  - statsmodels
  - sympy
  - tbb
  - tblib
  - terminado
  - testpath
  - textdistance
  - threadpoolctl
  - three-merge
  - tifffile
  - tk
  - toml
  - toolz
  - tornado
  - tqdm
  - traitlets
  - typed-ast
  - typing_extensions
  - ujson
  - unicodecsv
  - unixodbc
  - urllib3
  - watchdog
  - wcwidth
  - webencodings
  - werkzeug
  - wheel
  - widgetsnbextension
  - wrapt
  - wurlitzer
  - xlsxwriter
  - xlwt
  - xmltodict
  - xz
  - yaml
  - yapf
  - zeromq
  - zict
  - zipp
  - zlib
  - zope
  - zope.event
  - zope.interface
  - zstd
  