name: sez
channels:
  - defaults
dependencies:
  - anyio
  - argon2-cffi
  - async_generator
  - attrs
  - babel
  - backcall
  - blas
  - bleach
  - boost-cpp
  - brotlipy
  - bzip2
  - ca-certificates
  - cairo
  - certifi
  - cffi
  - cfitsio
  - chardet
  - click
  - click-plugins
  - cligj
  - cryptography
  - curl
  - dbus
  - defusedxml
  - entrypoints
  - expat
  - fiona
  - fontconfig
  - freetype
  - freexl
  - gcc_linux-64
  - gdal
  - geopandas
  - geos
  - geotiff
  - gettext
  - giflib
  - glib
  - hdf4
  - hdf5
  - icu
  - idna
  - importlib-metadata
  - importlib_metadata
  - intel-openmp
  - ipykernel
  - ipython_genutils
  - ipywidgets
  - jedi
  - jinja2
  - jpeg
  - json-c
  - json5
  - jsonschema
  - jupyter-packaging
  - jupyter_client
  - jupyter_core
  - jupyter_server
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - jupyterlab_widgets
  - kealib
  - krb5
#  - libblas
  - libboost
#  - libcblas
  - libclang
  - libcurl
#  - libcxx
  - libdap4
  - libedit
  - libffi
  - libgdal
#  - libgfortran
  - libiconv
  - libkml
#  - liblapack
  - libllvm10
  - libllvm9
  - libnetcdf
  - libopenblas
  - libpng
  - libpq
  - libsodium
  - libspatialindex
  - libspatialite
  - libssh2
  - libtiff
  - libwebp-base
  - libxml2
#  - llvm-openmp
  - lz4-c
  - markupsafe
  - mistune
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - munch
  - nbclassic
  - nbclient
  - nbconvert
  - nbformat
  - ncurses
  - nest-asyncio
  - notebook
  - nspr
  - nss
  - numpy
  - numpy-base
  - openjpeg
  - openssl
  - packaging
  - pandoc
  - pandocfilters
  - parso
  - pcre
  - pexpect
  - pickleshare
  - pip
  - pixman
  - poppler
  - poppler-data
  - postgresql
  - proj
  - prometheus_client
  - prompt_toolkit
  - ptyprocess
  - pycparser
  - pygments
  - pyopenssl
  - pyparsing
  - pyproj
  - pyqt
  - pyrsistent
  - pysocks
  - python
  - python-dateutil
  - pytz
  - pyzmq
  - qt
  - qtconsole
  - qtpy
  - rasterio
  - readline
  - requests
  - rtree
  - scipy
  - send2trash
  - setuptools
  - shapely
  - sip
  - six
  - sniffio
  - sqlite
  - tbb
  - terminado
  - testpath
  - tiledb
  - tk
  - tornado
  - traitlets
  - typing_extensions
  - urllib3
  - wcwidth
  - webencodings
  - wheel
  - widgetsnbextension
  - xerces-c
  - xz
  - zeromq
  - zipp
  - zlib
  - zstd
