name: sez
channels:
  - defaults
  - conda-forge
dependencies:
  - anyio
  - argon2-cffi
  - async_generator
  - attrs
  - babel
  - backcall
  - blas
  - bleach
  - boost-cpp
  - brotlipy
  - bzip2
  - ca-certificates
  - cairo
  - certifi
  - cffi
  - cfitsio
  - chardet
  - click
  - click-plugins
  - cligj
  - cryptography
  - curl
  - dbus
  - defusedxml
  - entrypoints
  - expat
  - fiona
  - fontconfig
  - freetype
  - freexl
  - gdal
  - geopandas
  - geos
  - geotiff
  - gettext
  - giflib
  - glib
  - hdf4
  - hdf5
  - icu
  - idna
  - importlib-metadata
  - importlib_metadata
  - intel-openmp
  - ipykernel
  - ipython_genutils
  - ipywidgets
  - jedi
  - jinja2
  - jpeg
  - json-c
  - json5
  - jsonschema
  - jupyter-packaging
  - jupyter_client
  - jupyter_core
  - jupyter_server
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - jupyterlab_widgets
  - kealib
  - krb5
  - libblas
  - libboost
  - libcblas
  - libclang
  - libcurl
  - libcxx
  - libdap4
  - libedit
  - libffi
  - libgdal
  - libgfortran
  - libiconv
  - libkml
  - liblapack
  - libllvm10
  - libllvm9
  - libnetcdf
  - libopenblas
  - libpng
  - libpq
  - libsodium
  - libspatialindex
  - libspatialite
  - libssh2
  - libtiff
  - libwebp-base
  - libxml2
  - llvm-openmp
  - lz4-c
  - markupsafe
  - mistune
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - munch
  - nbclassic
  - nbclient
  - nbconvert
  - nbformat
  - ncurses
  - nest-asyncio
  - notebook
  - nspr
  - nss
  - numpy
  - numpy-base
  - openjpeg
  - openssl
  - packaging
  - pandoc
  - pandocfilters
  - parso
  - pcre
  - pexpect
  - pickleshare
  - pip
  - pixman
  - poppler
  - poppler-data
  - postgresql
  - proj
  - prometheus_client
  - prompt_toolkit
  - ptyprocess
  - pycparser
  - pygments
  - pyopenssl
  - pyparsing
  - pyproj
  - pyqt
  - pyrsistent
  - pysocks
  - python
  - python-dateutil
  - python_abi
  - pytz
  - pyzmq
  - qt
  - qtconsole
  - qtpy
  - readline
  - requests
  - rtree
  - scipy
  - send2trash
  - setuptools
  - shapely
  - sip
  - six
  - sniffio
  - sqlite
  - tbb
  - terminado
  - testpath
  - tiledb
  - tk
  - tornado
  - traitlets
  - typing_extensions
  - tzcode
  - urllib3
  - wcwidth
  - webencodings
  - wheel
  - widgetsnbextension
  - xerces-c
  - xz
  - zeromq
  - zipp
  - zlib
  - zstd
  - pip:
    - address-parser
    - affine
    - alabaster
    - aniso8601
    - appdirs
    - arrow
    - asgiref
    - beautifulsoup4
    - binaryornot
    - boto
    - boto3
    - botocore
    - bs4
    - cached-property
    - censusgeocode
    - cfgv
    - ckanapi
    - codegen
    - colored
    - commonmark
    - configupdater
    - cookiecutter
    - cycler
    - decorator
    - deprecated
    - descartes
    - distlib
    - django
    - docopt
    - docutils
    - filelock
    - fredapi
    - fs
    - fuzzy
    - geoid
    - gitdb
    - gitpython
    - h5py
    - identify
    - imagesize
    - impyute
    - iniconfig
    - invoke
    - ipython
    - jinja2-time
    - jmespath
    - joblib
    - jupyter
    - jupyter-console
    - kiwisolver
    - latexcodec
    - livestats
    - lxml
    - mapclassify
    - markdown
    - matplotlib
    - matplotlib-inline
    - meta
    - metapack
    - metapack-build
    - metapack-github
    - metapack-jupyter
    - metapack-wp
    - metatab
    - metatabdecl
    - more-itertools
    - nameparser
    - networkx
    - nltk
    - nodeenv
    - nose
    - pandas
    - patsy
    - petl
    - phonetics
    - pillow
    - pluggy
    - poyo
    - pre-commit
    - prompt-toolkit
    - publicdata-census
    - py
    - py-stringmatching
    - pyaml
    - pybtex
    - pygithub
    - pyjwt
    - pynacl
    - pyqt5
    - pyqt5-qt5
    - pyqt5-sip
    - pyqtchart
    - pyqtchart-qt5
    - pyqtwebengine
    - pyqtwebengine-qt5
    - pyscaffold
    - pyscaffoldext-custom-extension
    - pyscaffoldext-dsproject
    - pyscaffoldext-markdown
    - pyscaffoldext-pyproject
    - pytest
    - python-louvain
    - python-slugify
    - python-wordpress-xmlrpc
    - pyyaml
    - rasterio
    - recommonmark
    - regex
    - requests-toolbelt
    - rowgenerators
    - s3transfer
    - scikit-learn
    - seaborn
    - semantic-version
    - setuptools-scm
    - simplegeneric
    - sklearn
    - smmap
    - snowballstemmer
    - snuggs
    - soupsieve
    - sphinx
    - sphinxcontrib-applehelp
    - sphinxcontrib-devhelp
    - sphinxcontrib-htmlhelp
    - sphinxcontrib-jsmath
    - sphinxcontrib-qthelp
    - sphinxcontrib-serializinghtml
    - sqlparse
    - statsmodels
    - stringdist
    - tableintuit
    - tabulate
    - terminaltables
    - text-unidecode
    - textdistance
    - threadpoolctl
    - toml
    - tomlkit
    - tox
    - tqdm
    - unicodecsv
    - virtualenv
    - wrapt
    - xlrd